<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Add this line to point to your Client project -->
		<SpaRoot>..\KapadaApplication\</SpaRoot>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\KapadaModel\KapadaModel.csproj" />
	</ItemGroup>

	<!-- Add these targets to build and copy the Client app -->
	<Target Name="BuildClient" BeforeTargets="Build">
		<Exec WorkingDirectory="$(SpaRoot)" Command="dotnet build" />
	</Target>

	<Target Name="CopyClientStaticFiles" AfterTargets="Build">
		<RemoveDir Directories="wwwroot" />
		<MakeDir Directories="wwwroot" />
		<!--<Copy SourceDirectory="$(SpaRoot)bin\Debug\net8.0\wwwroot" DestinationFolder="wwwroot" Recursive="true" />-->
	</Target>


</Project>






























<!--<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KapadaModel\KapadaModel.csproj" />
  </ItemGroup>

</Project>-->
